### ISSUE TITLE
Feature Request: Change GShade Preset depending on Zone

### ISSUE THREAD

**Issue by Willshaper** [MidoriKami/ChillFrames#1]
Not sure if it's possible, but i got a feature suggestion after seeing the Zone Change features in the plugin.

It would be nice if it could change your Gshade Preset depending on the zone you're currently in, as i have some presets that i really love, but make the game way too dark in some areas. So automatically switching to an alternate version would be super convenient.

This could also help with people using super fancy but heavyweight presets in overworld content, but use something more performance friendly in group content.

Anyway, thanks for an awesome plugin :)

-Willshaper

**Comment by MidoriKami** [comment]
Gshade is entirely external to FFXIV, I am not able to interface with gshade. Nor is this in the scope of this plugin.
