### ISSUE TITLE
API to allow other plugin to request disabling of frame limiting

### ISSUE THREAD

**Issue by Limiana** [MidoriKami/ChillFrames#10]
Hey, would you like an API for ChillFrames to allow other plugins to request disabling of frame limiting?

**Comment by MidoriKami** [comment]
Not really, this doesn't fit into any kind of typical workflow for a user, and is likely to cause confusion.

If disabling ChillFrames is necessary for compatibility with other plugins you can use the dalamud command handler to invoke "/chillframes disable" and "/chillframes enable" as needed.

That said, my secondary reason for refusal is that I see such IPC making the internal logic of ChillFrames even more confusing (more double negatives and whatnot) if it is done in a clean way I would be willing to merge a PR.

Of note would be making it clear to the user that something else has taken control of the settings.

**Comment by Limiana** [comment]
https://github.com/MidoriKami/ChillFrames/pull/11

I think this should be not too messy

**Comment by MidoriKami** [comment]
![image](https://github.com/MidoriKami/ChillFrames/assets/9083275/ecb69200-68fd-4793-b0bb-1b74839232e0)

Took a bit of a different approach. Should work fine.
