### ISSUE TITLE
GPose using both gpose and "cutscenes" conditions in limiter settings

### ISSUE THREAD

**Issue by ivalith** [MidoriKami/ChillFrames#12]
This is probably already known but just in case, I noticed entering gpose triggers both the gpose and cutscenes conditions and if both aren't unchecked then it won't limit FPS within gpose. Both screenshots are taken within gpose and I could confirm that the FPS wasn't limited in the second screenshot. 

![2023-10-11_03-52-19](https://github.com/MidoriKami/ChillFrames/assets/57418557/a9c39607-b7e7-4f02-86b1-f73d9e6f6bf2)
![2023-10-11_03-52-30](https://github.com/MidoriKami/ChillFrames/assets/57418557/962970af-24f5-44da-9a31-a77bc0949e23)

Limiting FPS for GPose is incredibly convenient so even if this isn't fixable thank you for making it easy to limit FPS when taking screenshots, it's such a major help.

**Comment by MidoriKami** [comment]
Literally working as intended. This is not a bug, this is how the game itself works. The game itself considers gpose a cutscenes and gpose.

In the second screenshot your fps was being limited by the ACTIVE limiter value.

**Comment by ivalith** [comment]
Okay, if that's how it works that's fine but for the sake of user's experience it might be worth notating it in the limiter settings, otherwise it will appear just not to work when someone tries just using the gpose limiter for a lower FPS impact with reshade et al.
