### ISSUE TITLE
No control over base state

### ISSUE THREAD

**Issue by Kosba2** [MidoriKami/ChillFrames#16]
Hi, first off I want to say that I love the idea of this plugin, I'm very thankful for it, it's something I want so that I can stop cooking my room and PC when I'm just lounging in town or something similar.

That said, as it currently is, it seems to default to the Lower Limit with any non-listed activity, just being in town, for example. My issue is that this is at-odds with the available conditions and if there is a solution for this involving the Vanilla Limiter as-well, then it is lost on me.

The use-case that I'd love would be to conditionally increase **and** decrease my framerate limit to target rates, but still have a midpoint somewhere between crafting (low framerate) and duties (high framerate). Currently because it defaults to the lower limit, or because there is no default condition, I cannot figure out how to create this.

i.e.
Default=60fps
Craft=20fps
Duty=165fps

**Comment by MidoriKami** [comment]
I have no plans to allow you to set three target FPS's.
