### ISSUE TITLE
Feature Request: "No" Condition or "Middle" Limit

### ISSUE THREAD

**Issue by bioandroid** [MidoriKami/ChillFrames#17]
Would it be possible to add a condition called "No Condition" that applies if none of the other conditions are met?

My ideal use of your plugin would be that when none of the conditions are met my game runs at the "Upper Limit" but when I'm Crafting (often with macros for long periods of time) the mod would activate the "Lower Limit" I have selected for the "Crafting" Condition.

Alternatively the option to set a "Middle Limit" that's active when no Conditions are met might be an even better solution.

Here's an example of how I'd use it:
Lower Limit: 30fps (Conditions: Crafting, Cutscenes, Island Sanctuary)
Middle Limit: 60fps (No Conditions Met)
Upper Limit: 120fps (Combat, Duties)

**Comment by MidoriKami** [comment]
Duplicate #16
