### ISSUE TITLE
Suggestion: Increase upper limit when lower limit exceeds value

### ISSUE THREAD

**Issue by SheepGoMeh** [MidoriKami/ChillFrames#18]
As it currently functions, increasing lower limit above upper limit leads to the value getting reset to its previous state.
My suggestion is to either have this approach be default or an optional setting:
Have upper limit set to whatever the lower limit value was set to only if it exceeds the value of the upper limit.

**Comment by MidoriKami** [comment]
It doesn't reset to previous state, it sets it equal to the current upper limit, which is more intuitive than having it adjust the upper limit without direct intention of editing the upper limit.

I don't think something that few people will ever experience is worth the effort to release an update.
