### ISSUE TITLE
Feature Request: add a 'general' adjustable condition

### ISSUE THREAD

**Issue by specturn** [MidoriKami/ChillFrames#19]
Hey! I really appreciate the mod. FF14's base framerate limiter is pretty rigid.

I was wondering if in the list of the customizable conditions, you could allow for a 'general' condition to use the upper limit value. So just walking around and exploring.

Use case: I would like to run the game at 120 fps, but I want to run cutscenes at 60 because physics gets wonky above that. (Very telling with all the wind whipping peoples hair in heavensward). I can't do this, as general wandering stays at the lower limit value.

Thank you!

**Comment by MidoriKami** [comment]
This is not in line with the intent of the plugin and would require a significant code overhaul to even attempt to implement. ChillFrames was not designed for that behavior.
