### ISSUE TITLE
Feature Request: AFK Mode

### ISSUE THREAD

**Issue by netrox91** [MidoriKami/ChillFrames#4]
Hey o/
First of all thank you for this amazing plugin :D 

Sometimes when i go AFK i alt+tab to trigger my AFK FPS Settings.
I was wondering if your plugin could detect when the player gets the AFK Flag and limits the FPS to a specific cap then?
So there's no need to make FF run in the background anymore?

Thanks!

**Comment by AkariCl** [comment]
Oh yes, that would be awesome! Its super chill to limit the fps that easy as its really not neccessary to keep them at 144 all the time. I also switch to low fps when I go afk - but always in FF`s menu settings. If that auto-afk fps mode could be implemented that would be really great! Actually thats a great idea! \o/

Anyway huge thank you already for you work! :D 💜  💜

**Comment by MidoriKami** [comment]
This is already available in final fantasy as vanilla settings option.

Take a look under system settings.

**Comment by netrox91** [comment]
Ohhhhh! Never saw that option :x
Thanks for pointing it out!

**Comment by AkariCl** [comment]
thats.. embarrassing xD well problem solved. Hell why I never recognized that, I even turned it on 36 manually when going afk. Anyway thanks for quick reply!
