### ISSUE TITLE
Disable during Duty Recorder

### ISSUE THREAD

**Issue by aradiel** [MidoriKami/ChillFrames#5]
Hey, I was going to take a look at some in-game recordings for P4S and noticed that despite having all the disable options marked it still limited my framerate. If I add the zone to the blacklist it would still work but I'd rather not have to do that for every zone I recorded stuff in since I use A Realm Recorded.

**Comment by MidoriKami** [comment]
I am taking a break from FFXIV at this time, and will not be adding features to my plugins until I return to the game in a few months. I will keep this issue open until I get around to implementing it, but it will not be anytime soon.

As a temporary solution you can use the chat command `/pcf on` and `/pcf off` to enable and disable the frame limiter manually. These commands can be used in a in-game macro.

**Comment by MidoriKami** [comment]
I had completely forgotten about this issue as it wasn't showing in my issue tracker =x
