### ISSUE TITLE
Not limiting frames in Diadem

### ISSUE THREAD

**Issue by Spanglish1337** [MidoriKami/ChillFrames#6]
![image](https://user-images.githubusercontent.com/89648547/188334068-d744e6ad-dc1f-481a-aaa6-e5df5a553886.png)

I added diadem but not working currently

**Comment by Spanglish1337** [comment]
Midori was online in discord and illustrated me in my mistake

**Comment by MidoriKami** [comment]
Actual bug, will address.

**Comment by Spanglish1337** [comment]
Ishgardian Restoration zone not working for the limiter aswell, so it might be more duties than I expected, that are affected

**Comment by Spanglish1337** [comment]
Sorry, I am learning how to use GitHub, whoops

**Comment by Spanglish1337** [comment]
![image](https://user-images.githubusercontent.com/89648547/188335339-47374830-fd53-41a0-82ec-4bccbbb838a2.png)

Nevermind, Ishgardian Restoration works with the limiter if you include it

So far, only Diadem has the issue

**Comment by MidoriKami** [comment]
Double check the behavior here to confirm if it is what you expect.

![image](https://user-images.githubusercontent.com/9083275/188338950-aeedfde5-309d-406b-8344-dd18c6fc5928.png)
![image](https://user-images.githubusercontent.com/9083275/188338961-f3006272-7bec-4a8a-92ab-93f2df6f2739.png)
![image](https://user-images.githubusercontent.com/9083275/188338986-70f4f991-e24a-475b-addd-dfbcc7d00d59.png)

**Comment by MidoriKami** [comment]
![image](https://user-images.githubusercontent.com/9083275/188339011-db54238a-9e8c-4cbb-bf1e-6a3865caba91.png)
![image](https://user-images.githubusercontent.com/9083275/188339016-f7a11756-e4f0-4517-aee6-2a2a57673285.png)
![image](https://user-images.githubusercontent.com/9083275/188339025-6ab92fbe-3cf2-4c36-b352-dd45af291f8b.png)

**Comment by Spanglish1337** [comment]
Yes, that would be correct, thank you!

I found today that the limiter was also being disabled inside housing areas for some reason, but it was fixed including the private cottages and apartments in the blacklist list, thankfully... but I swear I did not had to do that for housing areas, I don't know what I did or how it happened

**Comment by Spanglish1337** [comment]
![image](https://user-images.githubusercontent.com/89648547/188390200-b587a064-0663-4dee-bfa2-588691167b75.png)
Here, checking and unchecking the "disable during duty" was not working, limiter was inactive regardless. 

I don't know if it is related with the bug

**Comment by MidoriKami** [comment]
should be fixed in 44800e2dc71a2b61f702ad3e30608515054279c3
