### ISSUE TITLE
Suggestion: framerate when game is not in foreground 

### ISSUE THREAD

**Issue by AkazaRenn** [MidoriKami/ChillFrames#7]
I would like to limit the framerate of it to 1 FPS or so when waiting for queue, so I can play other 3D games without much performance loss. Thanks!

**Comment by MidoriKami** [comment]
I only allow a minimum frame rate of 10fps as below that value it becomes difficult to change any settings due to how the plugin works.

I will not be implementing a focus check as that would interact poorly with the already existing focus check the game has.
